import { addAPIProvider } from '@iconify/react'
import { ecoPublicPath } from './eco-mode'

/**
 * A4 — Iconify reads icon data from this app's own `<basePath>/iconify`
 * (`public/iconify`, generated by `scripts/make-iconify-offline.mjs`), never
 * from api.iconify.design: under the world's /builder the editor makes no
 * request outside its origin and base path. Runs before any icon renders.
 */
if (typeof window !== 'undefined') {
  addAPIProvider('', { resources: [`${window.location.origin}${ecoPublicPath('/iconify')}`] })
}
